### ISSUE TITLE
Link to documentation in top-level README is broken

### ISSUE THREAD

**Issue by glennklockwood** [ECP-CANDLE/Candle#7]
https://github.com/ECP-CANDLE/Candle/blob/master/README.md points to https://ecp-candle.github.io/Candle/ which does not exist.  Neither does https://ecp-candle.github.io/.

**Comment by hyoo** [comment]
The link was supposed to be https://ecp-candle.github.io/Candle/html/ . This is fixed. Thanks for reporting.
