### ISSUE TITLE
Document Summit run modes

### ISSUE THREAD

**Issue by jmjwozniak** [ECP-CANDLE/Candle#8]
Login, interactive, scheduled

**Comment by jmjwozniak** [comment]
Done here, just need some Sphinx help @hyoo 

https://github.com/ECP-CANDLE/Candle/tree/master/docs_/source/tutorials/examples/run-summit

**Comment by hyoo** [comment]
sure, i will take care of it.

**Comment by hyoo** [comment]
the page successfully created at https://ecp-candle.github.io/Candle/html/tutorials/examples/run-summit/README.html
